// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

// UpdateCounter provides a mock function with given fields: name, value
func (_m *Updater) UpdateCounter(name string, value int64) {
	_m.Called(name, value)
}

// UpdateGauge provides a mock function with given fields: name, value
func (_m *Updater) UpdateGauge(name string, value float64) {
	_m.Called(name, value)
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
